In [1]:
import tensorflow.compat.v1 as tf 

In [4]:
#the session graph must be define before the oprations 
with tf.Session() as sess : 
    c = tf.constant(20 ,tf.int32)
    print(sess.run(c))
    

20


In [11]:
with tf.Session() as sess : 
    c = tf.constant(20 ,tf.int32)
    v = tf.constant(30)
    x = c + v 
    print(sess.run(x))
    

50


In [15]:
with tf.Session() as sess :
    
    c = tf.constant(20 ,tf.int32)
    v = tf.constant(30)
    x = c + v 
    s = tf.Variable(30)
    print(sess.run(x))
    sess.run(tf.global_variables_initializer()) #important
    print(sess.run(s))

50
30


In [19]:
#change var value 
with tf.Session() as sess :
    
    c = tf.constant(20 ,tf.int32)
    v = tf.constant(30)
    x = c + v 
    s = tf.Variable(30)
    print(sess.run(x))
    sess.run(tf.global_variables_initializer()) #important
    print(sess.run(s))
    s = tf.Variable(35)
    sess.run(tf.global_variables_initializer())
    print(sess.run(s))
    z = tf.assign(s , 90)                      #to change var value 
    print(sess.run(z))

50
30
35
90


In [20]:
with tf.Session() as sess :
    a = tf.placeholder(tf.int32)
    b = a*2 + 8
    print(sess.run(b ,feed_dict = {a:2}))

12


In [21]:
with tf.Session() as sess :
    a = tf.placeholder(tf.int32)
    b = a*2 + 8
    print(sess.run(b ,feed_dict = {a:[2,3,4,5,6,7,8,8]}))

[12 14 16 18 20 22 24 24]


In [24]:
with tf.Session() as sess :
    a = tf.constant('hi ')
    b = tf.constant('python')
    x = tf.add(a , b)
    print(sess.run(x))
    

b'hi python'


In [25]:
with tf.Session() as sess :
    a = tf.constant(70)
    b = tf.constant(30)
    x = tf.add(a , b)
    print(sess.run(x))

100


In [27]:
with tf.Session() as sess :
    a = tf.constant(7)
    b = tf.constant(3)
    x = tf.multiply(a , b)
    print(sess.run(x))

21


In [30]:
with tf.Session() as sess :
    a = tf.constant(70)
    b = tf.constant(30)
    x = tf.subtract(a , b)
    print(sess.run(x))

40


In [31]:
with tf.Session() as sess :
    a = tf.constant(70)
    b = tf.constant(30)
    x = tf.divide(a , b)
    print(sess.run(x))

2.3333333333333335


In [32]:
with tf.Session() as sess :
    a = tf.constant(70)
    b = tf.constant(30)
    x = tf.pow(a , b)
    print(sess.run(x))

1073741824


In [33]:
with tf.Session() as sess :
    s1 = tf.constant([5,6,7,8])
    s2 = tf.constant(30)
    s3 = tf.add(s1,s2)
    print(sess.run(s3))

[35 36 37 38]


In [34]:
with tf.Session() as sess :
    s1 = tf.constant([5,6,7,8])
    s2 = tf.constant([5,6,7,8])
    s3 = tf.add(s1,s2)
    print(sess.run(s3))

[10 12 14 16]


In [35]:
with tf.Session() as sess :
    matrix1 = tf.constant([[5., 3.]])
    matrix2 = tf.constant([[2.],
                       [2.]])
    product = tf.matmul(matrix1, matrix2)
    print(sess.run(product))
    


[[16.]]


In [36]:
with tf.Session() as sess :
    matrix1 = tf.constant([[5,6,9,8],
                          [1,2,8,9],
                          [7,9,5,6],
                          [1,2,3,9]])


    matrix2 = tf.matrix_transpose(matrix1)
    print(sess.run(matrix2))
    


[[5 1 7 1]
 [6 2 9 2]
 [9 8 5 3]
 [8 9 6 9]]


In [37]:
graph = tf.get_default_graph()

In [39]:
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'add_1' type=AddV2>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'add_2' type=AddV2>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'add_3' type=AddV2>,
 <tf.Operation 'Variable/Initializer/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VarHandleOp>,
 <tf.Operation 'Variable/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'Variable/Assign' type=AssignVariableOp>,
 <tf.Operation 'Variable/Read/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'add_4' type=AddV2>,
 <tf.Operati

In [40]:
for operation in graph.get_operations() :
    print(operation.name)


Const
Const_1
Const_2
Const_3
add
Const_4
Const_5
add_1
Const_6
Const_7
add_2
Const_8
Const_9
add_3
Variable/Initializer/initial_value
Variable
Variable/IsInitialized/VarIsInitializedOp
Variable/Assign
Variable/Read/ReadVariableOp
init
Const_10
Const_11
add_4
Variable_1/Initializer/initial_value
Variable_1
Variable_1/IsInitialized/VarIsInitializedOp
Variable_1/Assign
Variable_1/Read/ReadVariableOp
Const_12
Const_13
add_5
Variable_2/Initializer/initial_value
Variable_2
Variable_2/IsInitialized/VarIsInitializedOp
Variable_2/Assign
Variable_2/Read/ReadVariableOp
init_1
Const_14
Const_15
add_6
Variable_3/Initializer/initial_value
Variable_3
Variable_3/IsInitialized/VarIsInitializedOp
Variable_3/Assign
Variable_3/Read/ReadVariableOp
Variable_4/Initializer/initial_value
Variable_4
Variable_4/IsInitialized/VarIsInitializedOp
Variable_4/Assign
Variable_4/Read/ReadVariableOp
init_2
Const_16
Const_17
add_7
Variable_5/Initializer/initial_value
Variable_5
Variable_5/IsInitialized/VarIsInitializedO

In [41]:
tf.enable_eager_execution()

In [47]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([5,6,7,8])
s3 = tf.add(s1,s2)
print(s3)

tf.Tensor([10 12 14 16], shape=(4,), dtype=int32)


In [50]:
# Define constant tensors
import numpy as np
a = tf.constant([[2., 1.],
                 [1., 0.]], dtype=tf.float32)
print("Tensor:\n a = %s" % a)
b = np.array([[3., 0.],
              [5., 1.]], dtype=np.float32)
print("NumpyArray:\n b = %s" % b)


Tensor:
 a = tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
NumpyArray:
 b = [[3. 0.]
 [5. 1.]]
